version: '3.8'
services:
  app:
    build:
      context: ./api-app
      dockerfile: Dockerfile
    volumes:
      - ./api-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test

